modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="darkdays"
version="1.0.0"
displayName="Darkdays"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://bitbucket.org/Rickroller01/darkdays1.0.0/src"
updateJSONURL="https://bitbucket.org/Rickroller01/darkdays1.0.0/src"
logoFile="logo.png"
authors="Rickroller01"

[[dependencies.darkdays]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




